"use client";

import { useLocale, useTranslations } from "next-intl";

export default function TermsPage() {
  const locale = useLocale();
  const t = useTranslations("legal");

  if (locale === "en") {
    return (
      <article className="prose dark:prose-invert max-w-none">
        <h1>{t("termsTitle")}</h1>
        <p className="text-muted-foreground text-sm">{t("lastUpdated")}: 2025-05-24</p>

        <h2>1. Service Description</h2>
        <p>
          &quot;Know Yourself&quot; is a self-discovery platform providing psychological tests
          and AI-powered analysis. The service is operated by a self-employed individual
          registered in the Russian Federation.
        </p>

        <h2>2. Account</h2>
        <ul>
          <li>You must be at least 16 years old to use the service</li>
          <li>You are responsible for maintaining the security of your account</li>
          <li>One account per person</li>
        </ul>

        <h2>3. Free and Paid Features</h2>
        <ul>
          <li><strong>Free:</strong> all tests, DeepSeek AI analysis</li>
          <li><strong>Paid:</strong> AI coaching sessions (per session), full personality report (one-time)</li>
        </ul>
        <p>Used sessions are non-refundable. Unused sessions do not expire.</p>

        <h2>4. Payments</h2>
        <p>
          Payments are processed by YuKassa. We accept bank cards and other methods supported by YuKassa.
          Prices are displayed in Russian rubles (RUB).
        </p>

        <h2>5. Intellectual Property</h2>
        <p>
          Test content, scoring algorithms, and AI prompts are our intellectual property.
          Your test results and AI conversations belong to you.
        </p>

        <h2>6. Limitations</h2>
        <ul>
          <li>Tests are not clinical diagnoses and do not replace professional advice</li>
          <li>AI analysis is generated by third-party models and may contain inaccuracies</li>
          <li>We do not guarantee uninterrupted service availability</li>
        </ul>

        <h2>7. Account Termination</h2>
        <p>
          You may delete your account at any time through Settings. All your data will be
          permanently removed. We may suspend accounts that violate these terms.
        </p>

        <h2>8. Governing Law</h2>
        <p>These terms are governed by the laws of the Russian Federation.</p>
      </article>
    );
  }

  return (
    <article className="prose dark:prose-invert max-w-none">
      <h1>{t("termsTitle")}</h1>
      <p className="text-muted-foreground text-sm">{t("lastUpdated")}: 24.05.2025</p>

      <h2>1. Описание сервиса</h2>
      <p>
        «Познай Себя» — платформа самопознания, предоставляющая психологические тесты
        и ИИ-анализ. Сервис управляется самозанятым, зарегистрированным в Российской Федерации.
      </p>

      <h2>2. Аккаунт</h2>
      <ul>
        <li>Для использования сервиса вам должно быть не менее 16 лет</li>
        <li>Вы несёте ответственность за безопасность вашего аккаунта</li>
        <li>Один аккаунт на человека</li>
      </ul>

      <h2>3. Бесплатные и платные функции</h2>
      <ul>
        <li><strong>Бесплатно:</strong> все тесты, ИИ-анализ DeepSeek</li>
        <li><strong>Платно:</strong> коуч-сессии (за сессию), полный отчёт о личности (разово)</li>
      </ul>
      <p>Использованные сессии не возвращаются. Неиспользованные сессии не сгорают.</p>

      <h2>4. Оплата</h2>
      <p>
        Платежи обрабатываются ЮKassa. Мы принимаем банковские карты и другие способы оплаты,
        поддерживаемые ЮKassa. Цены указаны в российских рублях (₽).
      </p>

      <h2>5. Интеллектуальная собственность</h2>
      <p>
        Содержание тестов, алгоритмы подсчёта и промпты ИИ являются нашей интеллектуальной
        собственностью. Ваши результаты тестов и ИИ-разговоры принадлежат вам.
      </p>

      <h2>6. Ограничения</h2>
      <ul>
        <li>Тесты не являются клиническим диагнозом и не заменяют профессиональную помощь</li>
        <li>ИИ-анализ генерируется сторонними моделями и может содержать неточности</li>
        <li>Мы не гарантируем бесперебойную работу сервиса</li>
      </ul>

      <h2>7. Удаление аккаунта</h2>
      <p>
        Вы можете удалить аккаунт в любое время через Настройки. Все ваши данные будут
        безвозвратно удалены. Мы можем заблокировать аккаунты, нарушающие эти условия.
      </p>

      <h2>8. Применимое право</h2>
      <p>Настоящее соглашение регулируется законодательством Российской Федерации.</p>
    </article>
  );
}
