-- Seed test categories
INSERT INTO public.test_categories (slug, name_ru, name_en, description_ru, description_en, icon, color, sort_order, question_count) VALUES
('psychology', 'Психология', 'Psychology', 'Личность, эмоции, стресс, саморефлексия', 'Personality, emotions, stress, self-reflection', 'Brain', '#8B5CF6', 1, 86),
('career', 'Карьера', 'Career', 'Профориентация, ценности, сильные стороны', 'Career orientation, values, strengths', 'Briefcase', '#3B82F6', 2, 80),
('intelligence', 'Интеллект', 'Intelligence', 'Когнитивные способности, типы мышления', 'Cognitive abilities, thinking styles', 'Lightbulb', '#F59E0B', 3, 24),
('habits', 'Привычки', 'Habits', 'Аудит привычек, продуктивность, формирование', 'Habit audit, productivity, habit formation', 'Target', '#10B981', 4, 25),
('family', 'Семья', 'Family', 'Привязанность, языки любви, динамика', 'Attachment, love languages, dynamics', 'Heart', '#EC4899', 5, 40),
('creativity', 'Творчество', 'Creativity', 'Дивергентное мышление, креативная уверенность', 'Divergent thinking, creative confidence', 'Palette', '#F97316', 6, 20),
('fun', 'Развлечения', 'Fun', 'Архетипы, квизы, что бы ты выбрал', 'Archetypes, quizzes, would you rather', 'Sparkles', '#6366F1', 7, 30);

-- Seed tests (referencing categories by slug)
INSERT INTO public.tests (category_id, slug, name_ru, name_en, description_ru, description_en, methodology, estimated_minutes, question_count, sort_order) VALUES
((SELECT id FROM public.test_categories WHERE slug = 'psychology'), 'big-five', 'Большая пятёрка (Big Five)', 'Big Five Personality Test', 'Определите ваши 5 ключевых черт личности: открытость, добросовестность, экстраверсия, дружелюбие, нейротизм. Тест основан на модели BFI-44.', 'Discover your 5 key personality traits: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism. Based on the BFI-44 model.', 'BFI-44 (NEO-PI-R short)', 15, 44, 1),
((SELECT id FROM public.test_categories WHERE slug = 'psychology'), 'eq', 'Эмоциональный интеллект', 'Emotional Intelligence', 'Оцените свой эмоциональный интеллект по 4 компонентам: самосознание, саморегуляция, эмпатия и социальные навыки.', 'Assess your emotional intelligence across 4 components: self-awareness, self-regulation, empathy, and social skills.', 'EQ self-assessment', 5, 20, 2),
((SELECT id FROM public.test_categories WHERE slug = 'psychology'), 'burnout', 'Стресс и выгорание', 'Stress & Burnout', 'Оцените уровень профессионального выгорания по трём шкалам: эмоциональное истощение, деперсонализация и профессиональная эффективность. Адаптация методики Маслач.', 'Assess your professional burnout level across three scales: Emotional Exhaustion, Depersonalization, and Personal Accomplishment. Adapted from the Maslach Burnout Inventory.', 'Maslach Burnout Inventory adapted', 6, 22, 3),
((SELECT id FROM public.test_categories WHERE slug = 'career'), 'riasec', 'Профориентация RIASEC', 'Career Orientation RIASEC', 'Определите ваш профессиональный тип по модели Холланда. 6 типов: Реалистичный, Исследовательский, Артистичный, Социальный, Предприимчивый, Конвенциональный.', 'Discover your professional type using Hollands model. 6 types: Realistic, Investigative, Artistic, Social, Enterprising, Conventional.', 'Holland RIASEC', 15, 60, 1),
((SELECT id FROM public.test_categories WHERE slug = 'career'), 'career-values', 'Карьерные ценности', 'Career Values', 'Определите ваши ключевые карьерные ценности и приоритеты. Что для вас важнее: деньги, свобода, влияние, стабильность или рост?', 'Discover your key career values and priorities. What matters most: money, freedom, impact, stability, or growth?', 'Career anchors adapted', 5, 20, 2),
((SELECT id FROM public.test_categories WHERE slug = 'intelligence'), 'gardner', 'Множественный интеллект', 'Multiple Intelligences', 'Определите ваш профиль множественного интеллекта по 8 типам: лингвистический, логико-математический, пространственный, музыкальный, телесно-кинестетический, межличностный, внутриличностный, натуралистический.', 'Discover your multiple intelligences profile across 8 types: Linguistic, Logical-Mathematical, Spatial, Musical, Bodily-Kinesthetic, Interpersonal, Intrapersonal, and Naturalistic.', 'Gardners MI Theory', 6, 24, 1),
((SELECT id FROM public.test_categories WHERE slug = 'habits'), 'habits', 'Аудит привычек', 'Habit Audit', 'Оцените качество ваших повседневных привычек в 5 сферах: здоровье, продуктивность, отношения, саморазвитие и отдых.', 'Assess the quality of your daily habits across 5 areas: health, productivity, relationships, self-development, and rest.', 'Habit audit framework', 6, 25, 1),
((SELECT id FROM public.test_categories WHERE slug = 'family'), 'attachment-style', 'Стиль привязанности', 'Attachment Style', 'Определите ваш тип привязанности в отношениях. Основано на модели ECR-R: тревожность и избегание.', 'Discover your attachment style in relationships. Based on the ECR-R model: anxiety and avoidance.', 'ECR-R', 8, 20, 1),
((SELECT id FROM public.test_categories WHERE slug = 'family'), 'love-languages', 'Языки любви', 'Love Languages', 'Узнайте ваш основной язык любви по модели Гэри Чепмена: слова поддержки, время, подарки, помощь, прикосновения.', 'Discover your primary love language using Gary Chapmans model: words of affirmation, quality time, gifts, acts of service, physical touch.', 'Chapman Love Languages', 5, 20, 2),
((SELECT id FROM public.test_categories WHERE slug = 'creativity'), 'creative', 'Уверенность в творчестве', 'Creative Confidence', 'Оцените свои творческие способности по 4 измерениям: оригинальность, беглость, гибкость и проработанность. Узнайте, в чём ваша творческая сила.', 'Assess your creative abilities across 4 dimensions: Originality, Fluency, Flexibility, and Elaboration. Discover your creative strengths.', 'Creativity self-assessment', 5, 20, 1),
((SELECT id FROM public.test_categories WHERE slug = 'fun'), 'mbti-light', 'Архетипы личности', 'Personality Archetypes', 'Определите свой тип личности из 16 архетипов. 4 измерения: энергия, восприятие, принятие решений, образ жизни.', 'Discover your personality type among 16 archetypes. 4 dimensions: energy, perception, decision-making, lifestyle.', 'MBTI-light adapted', 7, 30, 1);
